name: bev_swap_adaw_cosine_timm # only used for demonstration data api
root_dir: '/home/runshengxu/project/OpenCOOD/opv2v_data_dumping/train'
validate_dir: '/home/runshengxu/project/OpenCOOD/opv2v_data_dumping/validate'
#root_dir: '/data/opv2v/train'
#validate_dir: '/data/opv2v/validate'


train_params:
  batch_size: &batch_size 2
  epoches: &epoches 151
  eval_freq: 5
  save_freq: 5
  max_cav: &max_cav 5
  visible: true


fusion:
  core_method: 'CamLateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []


data_augment: []
add_data_extension: ['bev_dynamic.png', 'bev_static.png', 'bev_lane.png', 'bev_visibility.png', 'bev_visibility_corp.png']

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'RgbPreprocessor'
  args:
    bgr2rgb: true
    resize_x: &image_width 512
    resize_y: &image_height 512
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  # object evaluation range
  cav_lidar_range: &cav_lidar [-50, -50, -3, 50, 50, 1]


# anchor box related
postprocess:
  core_method: 'CameraBevPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

model:
  core_method: bev_swap
  args:
    target: &target 'dynamic' # dynamic, static or both
    encoder:
      conv_input_dim: 896
      conv_output_dim: 512
      num_layers: 34
      pretrained: true
      fpn: ~
    view_swap_fuse:
      input_dim: 512
      mlp_dim: 1024
      agent_size: 4
      window_size: 8
      dim_head: 32
      drop_out: 0.1
      depth: 2

    decoder:
      input_dim: 512
      num_layer: 2
      num_ch_dec: [64, 256]

    seg_head_dim: 64
    output_class: 2

loss:
  core_method: vanilla_seg_loss
  args:
    target: *target
    d_weights: 75.0
    s_weights: 15.0
    d_coe: 3.0
    s_coe: 1.0

optimizer:
  core_method: AdamW
  lr: 2e-4
  args:
    eps: 1e-10
    weight_decay: 1e-2

lr_scheduler:
    core_method: cosineannealwarm #step, multistep, Exponential and cosineannealwarm support
    epoches: *epoches
    warmup_lr: 2e-4
    warmup_epoches: 10
    lr_min: 5e-6
