name: point_pillar_late_fusion # only used for demonstration data api
root_dir: '/data/opv2v/train'
validate_dir: '/data/opv2v/validate'
#root_dir: '/home/hao/dataset/opv2v/train'
#validate_dir: '/home/hao/dataset/opv2v/train'

camera_to_lidar_ratio: 0
ego_mode: "lidar" # camera, lidar, mixed

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 8
  epoches: &epoches 151
  eval_freq: 2
  save_freq: 1
  max_cav: &max_cav 5
  visible: true


fusion:
  core_method: 'CamLiLateFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []


data_augment: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: CamLiPreprocessor
  cav_lidar_range: &cav_lidar [-102.4, -102.4, -3, 102.4, 102.4, 1]
  args:
    camera_preprocess:
      core_method: 'RgbPreprocessor'
      args:
        bgr2rgb: true
        resize_x: &image_width 512
        resize_y: &image_height 512
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]
      # object evaluation range
      cav_lidar_range: *cav_lidar
    lidar_preprocess:
      core_method: 'SpVoxelPreprocessor'
      args:
        voxel_size: &voxel_size [ 0.4, 0.4, 4 ]
        max_points_per_voxel: 32
        max_voxel_train: 32000
        max_voxel_test: 70000
      cav_lidar_range: *cav_lidar


# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: &achor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.27
  order: 'hwl' # hwl or lwh
  max_num: 120 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

model:
  core_method: 'point_pillar'
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    max_cav: *max_cav
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [ 64 ]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [ 3, 5, 8 ]
      layer_strides: [ 2, 2, 2 ]
      num_filters: [ 64, 128, 256 ]
      upsample_strides: [ 1, 2, 4 ]
      num_upsample_filter: [ 128, 128, 128 ]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 2 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3

    cls_head_dim: 256

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: AdamW
  lr: 2e-4
  args:
    eps: 1e-10
    weight_decay: 1e-2

lr_scheduler:
    core_method: cosineannealwarm #step, multistep, Exponential and cosineannealwarm support
    epoches: *epoches
    warmup_lr: 1e-3
    warmup_epoches: 10
    lr_min: 5e-6